blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    # path('', views.index, name='index'),
    path("", views.index, name="home"),
    path("post/<slug:slug>/", views.post, name="detail"),
    path("about/", views.about, name="about"),
    path("projects/", views.projects, name="projects"),
    path("resume/", views.resume, name="resume"),
    # path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

cnouboue_portfolio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings  # new
from django.conf.urls.static import static  # new
from blog import views as blog_views
from notebook import views as notebook_views
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from blog.models import Post
from blog.sitemaps import Static_Sitemap

from django.views.static import serve
from django.conf.urls import url


info_dict = {
    "queryset": Post.objects.filter(status=1),
    "date_field": "updated_on",
}

sitemaps = {
    "static": Static_Sitemap,
    "blog": GenericSitemap(info_dict, priority=0.6),
}


urlpatterns = [
    path("", blog_views.home, name="main_home"),
    path("", include("django.contrib.auth.urls")),  # Authentication urls
    path("admin/", admin.site.urls),  # Admin urls
    path("blog/", include("blog.urls"), name="blog"),
    path("notebook/", include("notebook.urls")),
    path("accounts/", include("allauth.urls")),
    # the sitemap
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    # For media files
    url(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    url(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]  # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = notebook_views.error_400
handler403 = notebook_views.error_403
handler404 = notebook_views.error_404
handler500 = notebook_views.error_500

notebook/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = "notebook"

urlpatterns = [
    # App index page
    path("", views.HomeView.as_view(), name="index"),
    ### Authentication urls
    # Signup / register and confirmation
    path("register/", views.register, name="register"),
    path("activate/<str:uidb64>/<str:token>/", views.activate, name="activate"),
    # Login
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    # Log out
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="registration/logout.html"),
        name="logout",
    ),
    # Profile
    path(
        "profile/", views.profileUserView.as_view(), name="profile-user"
    ),  # Url for authenticated user
    path("profiles/", views.profileListView, name="profile-list"),
    path(
        "profiles/<int:pk>/<str:slug>",
        views.profileDetailsView.as_view(),
        name="profile",
    ),  # Public user url
    path(
        "profiles/edit/<int:pk>", views.profileUpdateView, name="profile-edit"
    ),  # edit user page
    # path('profile/<str:uidb64>/', views.profile, name='profile'),  #User profile page
    # Password reset urls
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset.html",
            email_template_name="registration/password_reset_email.html",
        ),
        name="password_reset",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    ### CRUD urls for programs
    path("programs/", views.programListView, name="program-list"),
    path(
        "programs/<str:slug>/<int:pk>",
        views.ProgramDetailView.as_view(),
        name="program-detail",
    ),
    path(
        "programs/create/new", views.ProgramCreateView.as_view(), name="program-create"
    ),
    path(
        "programs/new/<str:media_type>/<int:tmdb_id>",
        views.ProgramNew,
        name="program-new",
    ),
    path("programs/<int:pk>/edit", views.ProgramUpdateView, name="program-edit"),
    path(
        "programs/delete/<int:pk>/",
        views.programDeleteView.as_view(),
        name="program-delete",
    ),
    path(
        "programs/<int:pk>/<str:slug>/similars",
        views.ProgramSimilarsView,
        name="program-similars",
    ),
    ### CRUD urls for views
    path(
        "view/<int:pk>",
        views.ViewProgramDetailView.as_view(),
        name="viewprogram-detail",
    ),
    path(
        "view/create/new",
        views.ViewProgramCreateView.as_view(),
        name="viewprogram-create",
    ),
    path(
        "view/edit/<int:pk>",
        views.ViewProgramUpdateView.as_view(),
        name="viewprogram-edit",
    ),
    path(
        "view/delete/<int:pk>/",
        views.ViewProgramDeleteView.as_view(),
        name="viewprogram-delete",
    ),
    ### Search URLs
    path(
        "searchposts",
        views.ViewSearch,
        name="search",
    ),
    ### Calendar Url
    path(
        "calendar/",
        # views.profileUserView.as_view(),
        views.CalendarView.as_view(),
        name="calendar",
    ),
    path(
        "calendar/public/<int:pk>/<str:slug>",
        views.profileUserView.as_view(),
        # views.CalendarView.as_view(),
        name="calendar-public",
    ),
    path(
        "graph/",
        views.graph,
        name="graph",
    ),
    path(
        "api/programs_by_provider/",
        views.programs_count_by_provider,
        name="programs-by-provider"
    ),
]

notebook/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import (
    UserUpdateForm,
    ProfileUpdateForm,
    ProgramUpdateForm,
    UserRegistrationForm,
)
from django import forms
from django.core.paginator import Paginator
import calendar
from django.db import IntegrityError

# Authentication & validation imports
from django.contrib.auth import login, authenticate
from django.views import generic
from django.http import HttpResponse, Http404
from django.template import loader
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.urls import reverse_lazy
from django.utils.html import mark_safe, format_html

# CRUD views
from .models import Program, Profile, ViewProgram
from django.views.generic import (
    CreateView,
    ListView,
    UpdateView,
    DeleteView,
    DetailView,
)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .utils import Calendar

# For search
import requests
import json
from datetime import datetime, timedelta, date
from .notebookfunctions import getProgramData, getProviders
import os

#Import other views
from .graphViews import graph, programs_count_by_provider



API_KEY = os.environ.get("TMDB_TOKEN", "test")

# Create your views here.


def index(request):
    return render(request, "notebook/index.html")


class HomeView(ListView):
    model = Program
    context_object_name = "programs"
    template_name = "notebook/index.html"
    ordering = ["-release_date"]


###################################################################
##                                                               ##
##                     PROFILE VIEWS                             ##
##                                                               ##
###################################################################


def profileListView(request):
    listProfiles = Profile.objects.all()
    context = {"listProfiles": listProfiles}
    template = "notebook/profiles_list.html"
    return render(request, template, context)


class profileDetailsView(ListView):
    model = ViewProgram
    template_name = "notebook/profile_detail.html"

    # template_name = 'notebook/calendar.html'
    # success_url = reverse_lazy("notebook:calendar")

    def get_date(self, req_day):
        if req_day:
            year, month = (int(x) for x in req_day.split("-"))
            return date(year, month, day=1)
        return datetime.today()

    def prev_month(self, d):
        first = d.replace(day=1)
        prev_month = first - timedelta(days=1)
        month = "month=" + str(prev_month.year) + "-" + str(prev_month.month)
        return month

    def next_month(self, d):
        days_in_month = calendar.monthrange(d.year, d.month)[1]
        last = d.replace(day=days_in_month)
        next_month = last + timedelta(days=1)
        month = "month=" + str(next_month.year) + "-" + str(next_month.month)
        return month

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = self.get_date(self.request.GET.get("month", None))
        cal = Calendar(d.year, d.month, self.kwargs["pk"])
        html_cal = cal.formatmonth(withyear=True)
        context["calendar"] = mark_safe(html_cal)
        context["prev_month"] = self.prev_month(d)
        context["next_month"] = self.next_month(d)

        profile_user = get_object_or_404(User, id=self.kwargs["pk"])
        context["profile_user"] = profile_user

        context["watchlist"] = ViewProgram.objects.filter(
            profile=profile_user.profile, status=0
        )
        context["in_progress"] = ViewProgram.objects.filter(
            profile=profile_user.profile, status=1
        )
        context["completed"] = ViewProgram.objects.filter(
            profile=profile_user.profile, status=2
        )

        return context

    # return render(request, template, context)


# @login_required
# def profileUserView(request):
class profileUserView(LoginRequiredMixin, ListView):

    model = ViewProgram
    template_name = "notebook/profile_user.html"

    # template_name = 'notebook/calendar.html'
    # success_url = reverse_lazy("notebook:calendar")

    def get_date(self, req_day):
        if req_day:
            year, month = (int(x) for x in req_day.split("-"))
            return date(year, month, day=1)
        return datetime.today()

    def prev_month(self, d):
        first = d.replace(day=1)
        prev_month = first - timedelta(days=1)
        month = "month=" + str(prev_month.year) + "-" + str(prev_month.month)
        return month

    def next_month(self, d):
        days_in_month = calendar.monthrange(d.year, d.month)[1]
        last = d.replace(day=days_in_month)
        next_month = last + timedelta(days=1)
        month = "month=" + str(next_month.year) + "-" + str(next_month.month)
        return month

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = self.get_date(self.request.GET.get("month", None))
        cal = Calendar(d.year, d.month, self.request.user.id)
        html_cal = cal.formatmonth(withyear=True)
        context["calendar"] = mark_safe(html_cal)
        context["prev_month"] = self.prev_month(d)
        context["next_month"] = self.next_month(d)

        context["watchlist"] = ViewProgram.objects.filter(
            profile=self.request.user.profile, status=0
        )
        context["in_progress"] = ViewProgram.objects.filter(
            profile=self.request.user.profile, status=1
        )
        context["completed"] = ViewProgram.objects.filter(
            profile=self.request.user.profile, status=2
        )

        return context

    # return render(request, template, context)


class CalendarView(ListView):
    model = ViewProgram
    template_name = "notebook/calendar.html"
    # success_url = reverse_lazy("notebook:calendar")

    def get_date(self, req_day):
        if req_day:
            year, month = (int(x) for x in req_day.split("-"))
            return date(year, month, day=1)
        return datetime.today()

    def prev_month(self, d):
        first = d.replace(day=1)
        prev_month = first - timedelta(days=1)
        month = "month=" + str(prev_month.year) + "-" + str(prev_month.month)
        return month

    def next_month(self, d):
        days_in_month = calendar.monthrange(d.year, d.month)[1]
        last = d.replace(day=days_in_month)
        next_month = last + timedelta(days=1)
        month = "month=" + str(next_month.year) + "-" + str(next_month.month)
        return month

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = self.get_date(self.request.GET.get("month", None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        # context['calendar'] = format_html(mark_safe("<div><h1> Hello </h1></div>"))
        context["calendar"] = html_cal
        context["prev_month"] = self.prev_month(d)
        context["next_month"] = self.next_month(d)

        return context


@login_required
def profileUpdateView(request, pk):

    if request.method == "POST":
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        u_form = UserUpdateForm(request.POST or None, instance=request.user)
        if p_form.is_valid() and u_form.is_valid():
            u_form.save()
            p_form.save()
            # messages.success(request,'Your Profile has been updated!')
            return redirect(
                "notebook:profile", request.user.id, request.user.profile.slug
            )

    else:
        p_form = ProfileUpdateForm(instance=request.user.profile)
        u_form = UserUpdateForm(instance=request.user)

    context = {"p_form": p_form, "u_form": u_form}
    return render(request, "notebook/profile_update.html", context)


# Register and Activate account views
def register(request):

    template = "registration/register.html"
    activation_mail_template = "registration/activation_mail_temp.html"

    if request.method == "POST":  # if the form has been submitted
        form = UserRegistrationForm(request.POST)  # form bound with post data

        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            to_email = form.cleaned_data.get("email")
            mail_subject = "Activate your Notebook account."
            message = render_to_string(
                activation_mail_template,
                {
                    "user": user,
                    "domain": current_site.domain,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": account_activation_token.make_token(user),
                },
            )

            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()

            # return redirect('notebook:profile')
            return HttpResponse(
                "Please confirm your email address to complete the registration"
            )

    else:
        form = UserRegistrationForm()
    return render(request, template, {"form": form})


# Activation view
def activate(request, uidb64, token):

    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

notebook/templates/notebook/edit.html
{% extends "notebook/base.html" %}
{% load bootstrap4 %}
{% block title %}Edit{% endblock title %}
{% block content %}
<h2>Edit your account</h2>
<p>You can edit your account using the follow form</p>
<form action="" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>
{% endblock content %}

notebook/templates/notebook/footer.html
{% block footer %}

<footer class="footer">
<small>
  © <time datetime="2021-01-14T00:12:08-07:00">2021</time>. All rights reserved.
</small>
</footer>

{% endblock footer %}

notebook/templates/notebook/index.html
{%extends 'notebook/base.html'%}

{% block title %}

  Notebook App 

{%endblock%} 

{% block content %}

<br/>
{% if user.is_authenticated %}
  <a class="btn btn-outline-primary" href="{% url 'notebook:program-create' %}" role="button"> Add program Manually</a> <br>
  <br>
{% endif %}
Search for a program to add it : <br>
<br/>
<form action="{% url 'notebook:search' %}" method="GET" value="{{request.GET.q}}">
Search <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search posts"/>
<input type="submit" name="submit" value="Search"/>
</form>

    {% if submitbutton == 'Search' and request.GET.q != '' %}

        {% if results %}
            <h1>Results for <b>{{ request.GET.q }}</b></h1>
            <br/><br/>

            <div class="posts">

            {% for result in results %}

                {% if result.overview != '' and result.poster_path is not None %}

                    <article class="post">
                      <a href="#"> 
                        <!-- Result title -->
                        <h3 class="post-title">
                          {% if result.media_type == 'tv' %}
                                {{ result.name }} | {{ result.media_type }}
                          {% elif result.media_type == 'movie' %}
                                {{ result.title }} | {{ result.media_type }}
                          {% endif %}
                        </h3>
                     
                      <!-- Result image -->
                      <img src="{{ 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2'|add:result.poster_path }}" width="100" height="150">
                    
                    </a>
                      <!-- Show an excerpt from the Result -->
                      <p id="synopsis">{{ result.overview }}</p> 

                      {% if user.is_authenticated %}
                        <a class="btn btn-outline-primary" href="{% url 'notebook:program-new' result.media_type result.id  %}" role="button"> Add program </a> <br>
                        <br>
                      {% endif %}
                    
                      
                    </article>

                {% endif %}

            {% endfor %}
        </div>


            {% else %}
            No search results for this query
          
        

        {% endif %}
    {% endif %}

{% endblock %}


{% block additional_js %}

  <style type="text/css">
    .post article{
        border-radius: 4px;
        background: #fff;
        box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05);
        transition: .3s transform cubic-bezier(.155,1.105,.295,1.12),.3s box-shadow,.3s -webkit-transform cubic-bezier(.155,1.105,.295,1.12);
        padding: 14px 80px 18px 36px;
        cursor: pointer;
        display:grid;
      }

      .post:hover{
        border-radius: 8px;
        padding: 12px 12px 12px 12px;
        transform: scale(1.05);
        box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
      }


  </style>



{% endblock %}

notebook/templates/notebook/navbar.html
{% block navbar %} 
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<h3 class="masthead-title">
    <div class="navbar">

        <span class="hidden clode-toggle" id="js-navbar-toggle-close" >
            <i class="fa fa-times"></i>
        </span>

        <span class="navbar-toggle" id="js-navbar-toggle">
            <i class="fa fa-bars"></i>
        </span>
        
      <div class="navbarContent" id="nav-menu">
      
        <a href="{% url 'notebook:index' %}" title="Home">Notebook APP</a>

            <!--- Display the About, Archive, etc. pages in the header --->
            &nbsp;&nbsp;&nbsp;<small><a class="nav-links" href="{% url 'notebook:program-list' %}"> Programs </a></small>
            &nbsp;&nbsp;&nbsp;<small><a class="nav-links" href="{% url 'notebook:profile-list' %}"> Profiles </a></small>

                {% if user.is_authenticated %}
                    &nbsp;&nbsp;&nbsp;<small><a class="nav-links" href="{% url 'notebook:profile-user' %}">My profile</a></small>
                    &nbsp;&nbsp;&nbsp;<small><a  class="nav-links" href="{% url 'notebook:logout' %}">Log out</a></small>
                   
                {% else %}
                    &nbsp;&nbsp;&nbsp;<small><a class="nav-links" href="{% url 'notebook:login' %}">Log In</a></small>
                    &nbsp;&nbsp;&nbsp;<small><a class="nav-links" href="{% url 'notebook:register' %}">Register</a></small>
                   
                {% endif %}
            
            &nbsp;&nbsp;&nbsp;<small><a class="nav-links" href="{% url 'blog:home' %}">Blog</a></small>
        
        </div>

      </div>
  </h3>
        <!---- I could use this to include the tag line, but it looks cluttered...
        <h3 class="masthead-title">
             <small>Machine Learning Tutorials and Insights</small>
        </h3>
        ----->
{% endblock navbar %}

notebook/templates/notebook/profile.html
{%extends 'notebook/base.html'%}
{% load crispy_forms_tags %}

{%block content%}
    <img src="{{user.profile.pic.url}}">
    <h2>{{user.username}}</h2>
    <p>{{user.email}}</p>
    <p>{{user.profile.bio}}</p>
    <br>

    {% if user.is_authenticated %}
    <h2> Update form : </h2>
    <form method='POST' enctype="multipart/form-data">
        {%csrf_token%}
        {{u_form|crispy}}
        {{p_form|crispy}}
        <button type='submit' class="btn btn-primary btn-block" >Update</button>
    </form>
    {% endif %}
{%endblock%}

notebook/templates/notebook/profile_detail.html
{%extends 'notebook/base.html'%}
{% load crispy_forms_tags %}

{% block title %}

    {{profile_user.username}} · Notebook App 

{%endblock%} 

{%block content%}

    <img src="{{profile_user.profile.pic.url}}">
    <h2>{{profile_user.username}}</h2>
    <p>{{profile_user.email}}</p>
    <p>{{profile_user.profile.bio}}</p>
    <br>
    {% if user.is_authenticated and profile_user.id == user.id %}
    <br>
        <p> To edit YOUR profile : </p>
        <a class="btn btn-outline-primary" href="{% url 'notebook:profile-edit' user.pk %}" role="button"> Edit </a> 
        <a class="btn btn-outline-primary" href="{% url 'notebook:viewprogram-create' %}" role="button"> Add view </a> <br>
        
    {% endif %}
    
    <hr><h3>Watchlist : </h3>
        <div class="wrapper">
            <div class="cards-slider owl-carousel">
                {% for view in watchlist %}
                <div class="card card-1">
                    <a href="{% url 'notebook:viewprogram-detail' view.id %}"> 
                        <div class="card-poster">
                            <img class="card-img" src="{{view.program.poster.url}}" alt="{{view.program.name}}">
                        </div>
                            <div class="card-corpus">
                            <div class="card-text">
                                <div class="card-title">{{view.program.name}}</div>
                                <p class="text-gray-700 text-base">
                                    {{view.comment|slice:":25"}} ...
                                </p>
                            </div>
                            </div>
                    </a>
                </div>        
                {% endfor %}
            </div>
        </div>

        


    <hr><h3>In progress : </h3>

        <div class="wrapper">
            <div class="cards-slider owl-carousel">
                {% for view in in_progress %}
                <div class="card card-1">
                        <a href="{% url 'notebook:viewprogram-detail' view.id %}"> 
                            <div class="card-poster">
                                <img class="card-img" src="{{view.program.poster.url}}" alt="{{view.program.name}}">
                            </div>
                            <div class="card-corpus">
                            <div class="card-text">
                                <div class="card-title">{{view.program.name}} </div>
                                <p class="text-gray-700 text-base">
                                    {{view.comment|slice:":25"}} ...
                                </p>
                            </div>
                            </div>
                        
                        </a>
                </div>
                {% endfor %}
            </div>
        </div>


    <hr><h3> Finished : </h3>

        <div class="wrapper">
            <div class="cards-slider owl-carousel">
            {% for view in completed %}
                <div class="card card-1">
                    <a href="{% url 'notebook:viewprogram-detail' view.id %}"> 
                        <div class="card-poster">
                            <img class="card-img" src="{{view.program.poster.url}}" alt="{{view.program.name}}" >
                        </div>
                        <div class="card-corpus">
                        <div class="card-text">
                            <div class="card-title">{{view.program.name}} </div>
                            <p class="text-gray-700 text-base">
                                {{view.comment|slice:":25"}} ...
                            </p>
                        </div>
                        </div>
                    </a>
                </div>
                
            {% endfor %}
            </div>
        </div>
 
    <br> 

    <!-- Calendar Block -->

    <div class="clearfix">
        <a class="btn btn-info left" href="{% url 'notebook:profile' profile_user.pk  profile_user.profile.slug %}?{{ prev_month }} "> Previous Month </a>
        <a class="btn btn-info right" href="{% url 'notebook:profile' profile_user.pk  profile_user.profile.slug %}?{{ next_month }} "> Next Month </a>
    </div>
    <br/>
    
    {{ calendar }}


{%endblock%}

{% block additional_js %}
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">

<script>

    // then trigger owl Carousel
    $(".cards-slider").owlCarousel({
      loop: false,
      autoplay: false,
      autoplayTimeout: 2000,
      autoplayHoverPause: false,
      responsive: {
        0:{
          items:1,
          nav:false
        },
        600:{
          items:2,
          nav:false
        },
        800:{
          items:3,
          nav:false
        }
      }
    });
  </script>


{%endblock%}

notebook/templates/notebook/program.html
Program view

notebook/templates/notebook/program_confirm_delete.html
{% extends "notebook/base.html" %}

{% block title %}

  Notebook App · Delete program 

{%endblock%} 

{% block content %}

        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Program</legend>
                <h2>Are you sure you want to delete {{ object.name }} ?</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'notebook:program-detail' object.slug object.id %}">Cancel</a>
            </div>
        </form>

{% endblock content %}

notebook/templates/notebook/program_edit.html
{% extends  'notebook/base.html' %}
{% load crispy_forms_tags %}

{% block title %} Add program {% endblock %}

{% block content %}

{% if user.is_authenticated %}
		
		  <div class="container h-100">
		    <div class="d-flex h-100 text-center align-items-center">
		      <div class="w-100 text-grey">
		        
		        <h4 class="card-title">Create a program </h4>

					<form method="post">
					{% csrf_token %}
					<input type="hidden" name="next" value="{{ next }}">

					{{ form|crispy }}

					<button type="submit" class="btn btn-primary btn-block">Create</button>
					</form>
					</br>

		      </div>
		    </div>
		  </div>

{% else %}

	<div class="container h-100">
		    <div class="d-flex h-100 text-center align-items-center">
		      <div class="w-100 text-grey">
		        
		        <h4 class="card-title">You need to login to access this page</h4>
		       </div>
		   </div>
	</div>


{% endif %}


		
{% endblock %}

notebook/templates/notebook/searchtemplate.html
<h1>Search Page</h1>

<br/>
<form action="{% url 'notebook:search' %}" method="GET" value="{{request.GET.q}}">
Search <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search posts"/>
<input type="submit" name="submit" value="Search"/>
</form>


{% if submitbutton == 'Search' and request.GET.q != '' %}
{% if results %}
<h1>Results for <b>{{ request.GET.q }}</b></h1>
<br/><br/>

{% for result in results %}

<img src="{{  'https://www.themoviedb.org/t/p/w600_and_h900_bestv2'|add:result.poster_path  }}" width="100" height="140">
<br/>

{{result.name}}
<br/>

{{result.origin_country}}
<br/>

{{result.overview}}
<br/>

{{result.id}}
<br/>

{% endfor %}
{% else %}
No search results for this query
{% endif %}
{% endif %}

notebook/templates/notebook/viewprogram_form.html
{%extends 'notebook/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<form method='POST' enctype="multipart/form-data">
    {%csrf_token%}
    {{ form|crispy }}
<button  type="submit" class="btn btn-primary btn-block">Submit</button>
</br>
{% if object.id is not null %}
    <a class="btn btn-danger" href="{% url 'notebook:viewprogram-delete' object.id %}" role="button"> Delete </a> <br>
{% endif %}
</form>
{% endblock %}