blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    # path('', views.index, name='index'),
    path("", views.index, name="home"),
    path("post/<slug:slug>/", views.post, name="detail"),
    path("about/", views.about, name="about"),
    path("projects/", views.projects, name="projects"),
    path("resume/", views.resume, name="resume"),
    # path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

cnouboue_portfolio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings  # new
from django.conf.urls.static import static  # new
from blog import views as blog_views
from notebook import views as notebook_views
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import GenericSitemap
from blog.models import Post
from blog.sitemaps import Static_Sitemap

from django.views.static import serve
from django.conf.urls import url


info_dict = {
    "queryset": Post.objects.filter(status=1),
    "date_field": "updated_on",
}

sitemaps = {
    "static": Static_Sitemap,
    "blog": GenericSitemap(info_dict, priority=0.6),
}


urlpatterns = [
    path("", blog_views.home, name="main_home"),
    path("", include("django.contrib.auth.urls")),  # Authentication urls
    path("admin/", admin.site.urls),  # Admin urls
    path("blog/", include("blog.urls"), name="blog"),
    path("notebook/", include("notebook.urls")),
    path("accounts/", include("allauth.urls")),
    # the sitemap
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    # For media files
    url(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    url(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
]  # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = notebook_views.error_400
handler403 = notebook_views.error_403
handler404 = notebook_views.error_404
handler500 = notebook_views.error_500

notebook/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = "notebook"

urlpatterns = [
    # App index page
    path("", views.HomeView.as_view(), name="index"),
    ### Authentication urls
    # Signup / register and confirmation
    path("register/", views.register, name="register"),
    path("activate/<str:uidb64>/<str:token>/", views.activate, name="activate"),
    # Login
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    # Log out
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="registration/logout.html"),
        name="logout",
    ),
    # Profile
    path(
        "profile/", views.profileUserView.as_view(), name="profile-user"
    ),  # Url for authenticated user
    path("profiles/", views.profileListView, name="profile-list"),
    path(
        "profiles/<int:pk>/<str:slug>",
        views.profileDetailsView.as_view(),
        name="profile",
    ),  # Public user url
    path(
        "profiles/edit/<int:pk>", views.profileUpdateView, name="profile-edit"
    ),  # edit user page
    # path('profile/<str:uidb64>/', views.profile, name='profile'),  #User profile page
    # Password reset urls
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset.html",
            email_template_name="registration/password_reset_email.html",
        ),
        name="password_reset",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="registration/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    ### CRUD urls for programs
    path("programs/", views.programListView, name="program-list"),
    path(
        "programs/<str:slug>/<int:pk>",
        views.ProgramDetailView.as_view(),
        name="program-detail",
    ),
    path(
        "programs/create/new", views.ProgramCreateView.as_view(), name="program-create"
    ),
    path(
        "programs/new/<str:media_type>/<int:tmdb_id>",
        views.ProgramNew,
        name="program-new",
    ),
    path("programs/<int:pk>/edit", views.ProgramUpdateView, name="program-edit"),
    path(
        "programs/delete/<int:pk>/",
        views.programDeleteView.as_view(),
        name="program-delete",
    ),
    path(
        "programs/<int:pk>/<str:slug>/similars",
        views.ProgramSimilarsView,
        name="program-similars",
    ),
    ### CRUD urls for views
    path(
        "view/<int:pk>",
        views.ViewProgramDetailView.as_view(),
        name="viewprogram-detail",
    ),
    path(
        "view/create/new",
        views.ViewProgramCreateView.as_view(),
        name="viewprogram-create",
    ),
    path(
        "view/edit/<int:pk>",
        views.ViewProgramUpdateView.as_view(),
        name="viewprogram-edit",
    ),
    path(
        "view/delete/<int:pk>/",
        views.ViewProgramDeleteView.as_view(),
        name="viewprogram-delete",
    ),
    ### Search URLs
    path(
        "searchposts",
        views.ViewSearch,
        name="search",
    ),
    ### Calendar Url
    path(
        "calendar/",
        # views.profileUserView.as_view(),
        views.CalendarView.as_view(),
        name="calendar",
    ),
    path(
        "calendar/public/<int:pk>/<str:slug>",
        views.profileUserView.as_view(),
        # views.CalendarView.as_view(),
        name="calendar-public",
    ),
    path(
        "graph/",
        views.graph,
        name="graph",
    ),
    path(
        "api/programs_by_provider/",
        views.programs_count_by_provider,
        name="programs-by-provider"
    ),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.sitemaps import ping_google
import logging

# Get an instance of a logger
logger = logging.getLogger(__name__)

# Create your models here.
STATUS = ((0, "Draft"), (1, "Published"))

CONTEXT = ((0, "Private"), (1, "School"), (2, "Pro"))


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    html_content = models.TextField(blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    main_image = models.ImageField(upload_to="images/", blank=True)
    github_link = models.CharField(
        max_length=500, default="https://github.com/cyrilhokage"
    )
    context = models.IntegerField(choices=CONTEXT, default=0)
    technos = models.CharField(max_length=500)
    summary = models.CharField(max_length=500)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/blog/" + self.slug

    # Overwrite save() method to send new sitemap to google when a post is updated
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        try:
            ping_google()
        except Exception:
            # Bare 'except' because we could get a variety
            # of HTTP-related exceptions.
            # Log an error message
            logger.error("Ping google for sitemaps failed.")
            pass

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.views import generic
from .models import Post


# Create your views here.

"""
class PostList(generic.ListView):

	latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)
    
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/index.html'

"""

"""
class PostDetail(generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    """


def home(request):
    return render(request, "index.html")


def index(request):
    post_list = Post.objects.order_by("-created_on")
    context = {"post_list": post_list}
    return render(request, "blog/index.html", context)


def post(request, slug):
    post = Post.objects.get(slug=slug)
    recomended_posts = Post.objects.filter(status=1).order_by("-created_on")[:3]
    context = {"post": post, "recomended_posts": recomended_posts}
    return render(request, "blog/article_detail.html", context)


def about(request):
    # post = Post.objects.get(slug=slug)
    # recomended_posts = Post.objects.order_by('-created_on')[:3]
    context = {}
    return render(request, "blog/about.html", context)


def projects(request):
    # post = Post.objects.get(slug=slug)
    # recomended_posts = Post.objects.order_by('-created_on')[:3]
    context = {}
    return render(request, "blog/projects.html", context)


def resume(request):
    # post = Post.objects.get(slug=slug)
    # recomended_posts = Post.objects.order_by('-created_on')[:3]
    context = {}
    return render(request, "blog/resume.html", context)

blog/templates/blog/about.html
{% extends "blog/base.html" %} 

{% block title %}

    {{ post.title }}  A propos

{%endblock%} 

{% block content %}
  {% load static %}
  <!-- partial:index.partial.html <div id="particles-js"></div>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<link rel="stylesheet" href="{% static 'blog/css/style_particles.css' %}" >   -->
  
  

  <article class="page">
          
          <h2 class="page-title"> A propos </h2>
                <p><img class="profile_img" src="{% static 'img/profile.jpg' %}" alt="Profile picture"></p>
              <div class="main_text">
                    <p> Je suis passionné par l'intelligence artificielle, le DevOps,
                       et tout ce qui se rapproche de l'informatique et des nouvelles technologies.</p>  
                  </br>
                    <p>Cet espace est dédié à des projets et travaux personnels.
                      Ils sont constitués de projets personnels
                      pour me familiariser avec les technologies qui me passionnent, notamment celles
                      autour du big data, de l'IA, de l'étude du language naturel et du DevOps.</p>
                    </br></br>
                    <p>Je suis aussi présent ailleurs sur le web : </p>

                    <ul>
                      <li> <a href="https://www.linkedin.com/in/cyrille-noubou%C3%A9-21a4a4a0/">LinkedIn</a></li>
                      <li> <a href="https://github.com/cyrilhokage" >GitHub</a> </li>
                    </ul>
              </div>

              <h2 id="education--experience">Parcours </h2>

              <table>
                <tbody><tr><td>2019 - 2020 </td><td>TELECOM Paris, Master spécialisé Big Data et gestion des données</td></tr>
                <tr><td>2016 – 2019</td><td>ESIGELEC, Ecole d'ingénieurs généraliste</td></tr>
                <tr><td>2014 - 2016</td><td>CPII - ESIGELEC, Classes préparatoires intégrées</td></tr>
                <tr><td>2014</td><td> Baccalauréat C</td></tr>
              </tbody></table>

      
    </article>

    <!-- partial -->
    <script src='https://cldup.com/S6Ptkwu_qA.js'></script>
    

{%endblock%}



{% block additional_js %}

<!--<script type="text/javascript"  src="{% static 'blog/js/script_particles.js' %}"></script> -->
<script type="text/javascript"  src="{% static 'blog/js/script_particles.js' %}"></script>
<style type="text/css">

.page{
  background-color:white;
  padding-right:20px;
  border-radius: 10px;
}


.profile_img {

  max-width: 50%;
  height: auto;
  padding-right: 15px;
float: left;
}

.main_text {
  padding-top: 90px;
  padding-left: 10px;
display: inline-flexbox;
} 

</style>

{% endblock %}

blog/templates/blog/animated_drone.html
{% block animated_drone %}
<div class="drone" id="drone">
  <div class="overlay"></div>
  <img src="http://svgur.com/i/7fM.svg" class="droneBody">
  </img>
  <img src="http://svgur.com/i/7gx.svg" class="prop prop1">
  </img>
  <img src="http://svgur.com/i/7gx.svg" class="prop prop2">
  </img>
  <img src="http://svgur.com/i/7gx.svg" class="prop prop3">
  </img>
  <img src="http://svgur.com/i/7gx.svg" class="prop prop4">
  </img>
</div>

<style type="text/css">
  body{
 /* background: #DFE9EF; */
  width: 100vw;
  height: 100vh;
}
.drone{
  position: relative;
  margin: 100px auto;
  width: 300px;
  height: 300px;
  animation: all 2.5s infinite ease-in-out;
  transition: all .1s;
}
.droneBody{
  width: 338px;
  height: 299px;
  animation: drone 3s infinite ease-in-out;
  overflow: hidden;
  
}
.overlay{
  width: 100px;
  height: 219px;
  z-index: 1;
  position: absolute;
  top: 14px;
  left: 120px;

  /* Rectangle 3: */
  background-image: linear-gradient(-237deg, rgba(238,238,238,.8) 20%, rgba(216,216,216,0.00) 79%);
  opacity: .6;
  animation: overlay 2.5s infinite ease-in-out;
}
.prop{
  width: 62px;
  height: 112px;
  
  transform-origin: 47.2% 50.1%;
}
.prop1{
  position: absolute;
  left: 16px;
  top: -26px;
  animation: prop .5s infinite linear;
}
.prop2{
  position: absolute;
  right: -25px;
  top: -27px;
  animation: ccw .5s infinite linear;
}
.prop3{
  position: absolute;
  right: -26px;
  bottom: 12px;
  animation: prop .5s infinite linear;
}
.prop4{
  position: absolute;
  left: 16px;
  bottom: 9px;
  animation: ccw .5s infinite linear;
  
}

@keyframes prop{
  100%{
    transform: rotate(920deg);
  }
}
@keyframes ccw{
  100%{
    transform: rotate(-920deg);
  }
}
@keyframes drone{
  0%{
    filter: drop-shadow( 0 10px 0px rgba(0,0,0,.2));
  }
  50%{
    filter: drop-shadow( 0 25px 3px rgba(0,0,0,.1));
  }
  100%{
    filter: drop-shadow( 0 10px 0px rgba(0,0,0,.2));
  }
}
@keyframes all{
  50%{
    transform: scale(1.08) rotateZ(1.5deg) rotateY(10deg);
  }
}
@keyframes overlay{
  50%{
    transform: scale(1) ;
    opacity: .2;
  }
}
  
</style>
{% endblock %}

blog/templates/blog/article.html
Bonjour voici un post

blog/templates/blog/article_detail.html
{% extends "blog/base.html" %} 

{% block title %}

    {{ post.title }}  

{%endblock%} 

{% block content %}
{% load static %}

  <div class="row">

      <article class="post">
              <h1 class="post-title">{{ post.title }}</h1>
              <time datetime="2019-09-19T08:00:00-07:00" class="post-date">{{ post.updated_on }}</time>
             
             <img src="{{ post.main_image.url }}" alt="{{ post.title }}" width="100%" height="auto">
          
            <p> <!-- Content from README.md file -->
                <div id="content"></div>
                <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
                <script type="text/javascript"> 
                    document.getElementById('content').innerHTML =
                    marked(`{{post.content}}`);
                </script>
            </p>
          </br>
          
          
          <p><a href="#" class="fa fa-github"></a>  GitHub link : <a href="{{post.github_link}}">click here</a></p>

          {% if post.html_content is not null %}
                  {{post.html_content | safe }}
          {% endif %}
          
        </article>
    </div>

    <!-- Related Articles -->
    <aside class="related">

        <div class="row">
            <h3>Most recents posts :</h3>
        </div>
        <br/>
        <div class="row">

            <div class="container">
                  
                    {% for recomended in recomended_posts %} 

                        <a href="{% url 'blog:detail' recomended.slug %}" style="text-decoration: none;">

                            <div class="row">
                              <div class="card card-1" style="background-image:url(https://ionicframework.com/img/getting-started/components-card.png);">
                                <h3>{{ recomended.title }}</h3>
                                <p>
                                <small><time datetime="{{ recomended.created_on }}" > {{ recomended.created_on }} </time></small></p>
                              </div>
                            </div>
                          </a>

                    {% endfor %} 
               
            </div> 

            <style type="text/css">
              .card{
                  border-radius: 4px;
                  background: #fff;
                  box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05);
                    transition: .3s transform cubic-bezier(.155,1.105,.295,1.12),.3s box-shadow,.3s -webkit-transform cubic-bezier(.155,1.105,.295,1.12);
                /*padding-top: 1px;*/
                padding: 0px 40px 0px 15px;
                margin-bottom: 15px;
                cursor: pointer;
                width:100%;
                height: 105px; 
              }

              .card:hover{
                   transform: scale(1.05);
                box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
              }

              .card h3{
                font-weight: 600;
              }

              .card img{
                position: absolute;
                top: 20px;
                right: 15px;
                max-height: 120px;
              }

              .card-1{
                    background-repeat: no-repeat;
                  background-position: right;
                  margin-right:auto;
                  /*background-size: 80px;*/
              }


              .card-2{
                 background-image: url(https://ionicframework.com/img/getting-started/components-card.png);
                    background-repeat: no-repeat;
                  background-position: right;
                  background-size: 80px;
              }

              .card-3{
                 background-image: url(https://ionicframework.com/img/getting-started/theming-card.png);
                    background-repeat: no-repeat;
                  background-position: right;
                  background-size: 80px;
              }

              @media(max-width: 500px){
                .card{
                  /*margin: 20px;*/
                }
              }
            </style>

        </div>

    </aside>

{%endblock%}

blog/templates/blog/asuppr.html
<body><div id="MathJax_Message" style="display: none;"></div>

    <div class="container content">
      <header class="masthead">
        <h3 class="masthead-title">
          <a href="/" title="Home">Chris McCormick</a>

          <!--- Display the About, Archive, etc. pages in the header --->
          
              &nbsp;&nbsp;&nbsp;<small><a href="/about/">About</a></small>
          
              &nbsp;&nbsp;&nbsp;<small><a href="/tutorials/">Tutorials</a></small>
          
              &nbsp;&nbsp;&nbsp;<small><a href="/archive/">Archive</a></small>
          

        </h3>
        <!---- I could use this to include the tag line, but it looks cluttered...
        <h3 class="masthead-title">
             <small>Machine Learning Tutorials and Insights</small>
        </h3>
        ----->

      </header>

      <main>
        <article class="page">
  <h1 class="page-title">About</h1>
  <p><img src="https://chrisjmccormick.files.wordpress.com/2012/12/chrisprofile_portrait_300px.jpg" alt="Profile picture"></p>

<p>I love the field of Machine Learning! Such a fascinating and impactful subject, and also one that’s hard to master.</p>

<p>I also happen to love the challenge of explaining difficult topics well. I’ve brought together my love of ML and my passion for making tutorials to form my online education business at <a href="https://www.chrismccormick.ai">ChrisMcCormick.AI</a>, which is now my full-time job.</p>

<p>Here are some of the places you can find me and my work:</p>

<ul>
  <li>Written <a href="http://www.mccormickml.com/tutorials/">tutorials</a> on this blog.
    <ul>
      <li>Typically with (thoroughly!) commented example code on <a href="http://github.com/chrisjmccormick/">GitHub</a>.</li>
    </ul>
  </li>
  <li><a href="http://bit.ly/2X8tcXE">eBooks</a> and <a href="https://www.chrismccormick.ai/word2vec-the-course">Video Courses</a> at ChrisMcCormick.AI.</li>
  <li><a href="https://www.quora.com/profile/Chris-McCormick-12">Answers on Quora</a></li>
  <li>Insights &amp; answers on my <a href="https://www.youtube.com/channel/UCoRX98PLOsaN8PtekB9kWrw/">YouTube channel</a> (<em>Coming Soon!</em>).</li>
</ul>

<h1 id="education--experience">Education &amp; Experience</h1>

<table>
  <tbody><tr><td>2006</td><td>B.S. Electrical Engineering, Stanford University</td></tr>
  <tr><td>2006 – 2011</td><td>Embedded Software Engineer, Texas Instruments</td></tr>
  <tr><td>2012 - 2014</td><td>Applications &amp; Development Engineer, CogniMem</td></tr>
  <tr><td>2015 - 2018</td><td>Research &amp; Applications, Nearist</td></tr>
  <tr><td>2019 - Present</td><td>Founder, ChrisMcCormick.AI</td></tr>
</tbody></table>


</article>

      </main>
      
      <footer class="footer">
        <small>
          © <time datetime="2019-12-23T08:23:59-08:00">2019</time>. All rights reserved.
        </small>
      </footer>
    </div>

    
     <script>
       (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
       (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
       })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
       ga('create', 'UA-76624103-1', 'auto');
       ga('send', 'pageview');
     </script>
    
  

</body>

blog/templates/blog/footer.html

{% block footer %}

        <footer class="footer">
        <small>
          © <time datetime="2021-01-14T00:12:08-07:00">2021</time>. All rights reserved.
        </small>
      </footer>

{% endblock footer %}

blog/templates/blog/index.html
{% extends "blog/base.html" %} 

{% block title %}

  Cyrille NOUBOUE · Machine Learning Tutorials and Insights  

{%endblock%} 

{% block content %}



        <div class="posts">
  
          {% for post in post_list %}
              {% if post.status == 1 %}
                    <article class="post">
                      <a href="{% url 'blog:detail' post.slug %}"> 
                        <!-- Post title -->
                        <h3 class="post-title">
                            {{ post.title }}
                        </h3>
                      
                      <!-- Date of the post -->
                      <time datetime="2019-09-19T08:00:00-07:00" class="post-date">{{ post.Author }} | {{ post.created_on}} </time>
                      
                      <!-- Post image -->
                      <img src="{{ post.main_image.url }}" alt="post.tilte" width="100%" height="auto">
                    
                    </a>
                      <!-- Show an excerpt from the article -->
                      <p id="introduction">{{post.summary|slice:":200" }}</p> 
                    
                      
                      <!-- Comment count 
                      <a href="/2019/09/19/XLNet-fine-tuning/#disqus_thread">6 Comments</a>
                      -->
                      
                    </article>
              {% endif %} 

          {% endfor %}  
          
        </div>

        

            <div class="pagination">
              
                <a class="pagination-item older" href="#">Older</a>
              
              
                <div class="pagination-item newer">Newer</div>
              
            </div>
          


        {% load static %}
        <!-- bloc de l'image pour l'effet de srolling désynchronisé 
        <span class="rellax" data-rellax-speed="2" style="left: 600px;bottom: 25px;"><img src="{% static 'blog/img/kowalski.png' %}"></span>
        -->
        
        

        <!-- Code for comment counts -->
     <!--   <script id="dsq-count-scr" src="//mccormickml.disqus.com/count.js" async=""></script> -->

{% endblock %}


{% block additional_js %}

            <!-- Particular JS scripts Goes here  -->
 <!--  <script src="{% static 'js/script_shapes.js' %}"></script>
       <script src="{% static 'blog/js/vanta.birds.min.js' %}"></script>

        <script>
        VANTA.BIRDS({
          el: "#mainContent",
          backgroundColor: 0xffffff,
          /*color1: 0x181717,
          color2: 0xcbf7,*/
          color1: 0x0,
          color2: 0x9060A8,
          birdSize: 0.40,
           quantity: 3.00
        })
        </script> -->

  <style type="text/css">
    .post article{
          border-radius: 4px;
          background: #fff;
          box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05);
            transition: .3s transform cubic-bezier(.155,1.105,.295,1.12),.3s box-shadow,.3s -webkit-transform cubic-bezier(.155,1.105,.295,1.12);
        padding: 14px 80px 18px 36px;
        cursor: pointer;
      }

      .post:hover{
        border-radius: 8px;
        padding: 12px 12px 12px 12px;
        transform: scale(1.05);
        box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
      }


  </style>



{% endblock %}

blog/templates/blog/navbar.html


{% block navbar %} 
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<h3 class="masthead-title">
    <div class="navbar">

        <span class="hidden clode-toggle" id="js-navbar-toggle-close" >
            <i class="fa fa-times"></i>
        </span>

      <span class="navbar-toggle" id="js-navbar-toggle">
          <i class="fa fa-bars"></i>
      </span>


      <div class="navbarContent" id="nav-menu" >
      
      
            <a href="{% url 'main_home' %}"  title="Home">Cyrille NOUBOUE</a>

            <!--- Display the About, Archive, etc. pages in the header --->

                &nbsp;&nbsp;&nbsp;<small><a class="nav-links" href="{% url 'blog:about' %}">A propos</a></small>

                &nbsp;&nbsp;&nbsp;<small><a class="nav-links" href="{% url 'blog:home' %}">Projets</a></small>
                    
                {% load static %}
                &nbsp;&nbsp;&nbsp;<small><a class="nav-links" href="{% url 'blog:resume' %}">CV</a></small>

                &nbsp;&nbsp;&nbsp;<small><a class="nav-links" href="{% url 'blog:resume' %}">Contact</a></small>

                &nbsp;&nbsp;&nbsp;<small><a class="nav-links" href="{% url 'notebook:index' %}">Notebook App</a></small>
            
        </div>

      </div>
  </h3>
        <!---- I could use this to include the tag line, but it looks cluttered...
        <h3 class="masthead-title">
             <small>Machine Learning Tutorials and Insights</small>
        </h3>
        ----->


{% endblock navbar %}